language: python

sudo: required

python:
    - '3.6'
    - '3.7'

install:
    - pip install -r requirements_lego.txt
    - pip install -r tests/requirements_lego.txt

cache: pip

script:
    - python setup.py check -m -s
    - python setup.py build_ext --inplace
    - coverage run --source keras_retinanet -m py.test keras_retinanet tests --doctest-modules --forked --flake8

after_success:
    - coverage xml
    - coverage report
    - codecov
